# Generated by Django 5.2.15 on 2026-06-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skripsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=20)),
                ('nama', models.CharField(max_length=100)),
                ('judul', models.TextField()),
                ('dosen_pembimbing', models.CharField(max_length=100)),
            ],
        ),
    ]
