# Generated by Django 5.2.15 on 2026-06-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skripsi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skripsi',
            name='semester',
            field=models.IntegerField(default=1),
        ),
    ]
